# Generated by Django 5.1.3 on 2024-11-13 11:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id_customer', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('surname', models.CharField(max_length=55)),
                ('birth_year', models.DateField()),
                ('location', models.CharField(max_length=25)),
                ('address', models.CharField(max_length=150)),
                ('job_type', models.CharField(max_length=35)),
                ('create_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
